# Numpy Practice

Proceed with this challenge only if you feel comfortable with Monday's and Tuesday's assignments. If you feel you should spend this time reviewing the lecture/assignments, please do that instead.



---



## 1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

In [1]:
import numpy as np

l = [12.23, 13.32, 100, 36.32]
print("Original List:",l)

Original List: [12.23, 13.32, 100, 36.32]


In [4]:
np.array(l)

array([ 12.23,  13.32, 100.  ,  36.32])

## 2. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.



In [5]:
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]



#That's what this is
---



## 3. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.

In [6]:
x = np.zeros(10)
print(x)
print("Update sixth value to 11")
x[6] = 11
print(x)
# WAT. The answer is already here.

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


## 4. Write a NumPy program to create a array with values ranging from 12 to 38.

In [8]:
x = np.arange(12, 38)
print(x)
np.array(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])



---



## 5. Write a NumPy program to reverse an array (first element becomes last).

In [9]:
x = np.arange(12, 38)
print("Original array:")
print(x)
np.array(x[::-1])

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])



---



## 6. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [10]:
x = np.ones((5,5))
print("Original array:")
print(x)


Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
# def hollow():
#     x = np.ones((5,5))
#     for i in x[1:-1]:
#         for j in i[1:-1]:
#             j = 0
#     return x
# hollow()

In [24]:
[1 for i in range(5)]

[1, 1, 1, 1, 1]

In [26]:
np.concatenate([[1], [0 for i in range(5-2)], [1]])

array([1, 0, 0, 0, 1])

In [29]:
np.concatenate([[np.concatenate([[1], [0 for i in range(5-2)], [1]])] for i in range(5-2)])

array([[1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1]])

In [32]:
def hollow(width, height):
    bookends = [1 for i in range(width)]
    middle = np.concatenate([[np.concatenate([[1], [0 for i in range(width-2)], [1]])] \
                                for i in range(height-2)])
    x = np.vstack([bookends, middle, bookends])
    return x

hollow(5, 5)


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [33]:
hollow(10, 12)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

## 7. Write a NumPy program to find common values between two arrays.

In [34]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]


In [36]:
np.intersect1d(array1, array2)

array([10, 40])

## 8. Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.

In [39]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = np.array([10, 30, 40, 50, 70])
print("Array2: ",array2)

Array1:  [ 0 10 20 40 60 80]
Array2:  [10 30 40 50 70]


In [43]:
np.intersect1d(array1, array2)

array([10, 40])

In [53]:
a = np.union1d(array1, array2).tolist()
remove = np.intersect1d(array1, array2).tolist()
f = np.delete(np.array([3, 4]), [3])
f

C:\Users\Cooper\Anaconda3\envs\Mike\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: in the future out of bounds indices will raise an error instead of being ignored by `numpy.delete`.
  This is separate from the ipykernel package so we can avoid doing imports until


array([3, 4])



---



## 9. Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

In [ ]:
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)



---



## 10. Write a NumPy program to create a new shape to an array without changing its data.

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6])



---



Congrats, now go review yesterday's material.